  spring:
    jpa:
     hibernate:
       ddl-auto: create-drop
       show-sql: true

    datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/spbatchdb
     username: root
     password: Vasant@123

    batch:
      jdbc:
       initialize-schema: ALWAYS
      job:
        enabled: false

